/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://2sk4cdnbbvguxagvu4227yx4we.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dmq4ls56hjgynhde4qaedreet4",
    "aws_cognito_identity_pool_id": "us-west-2:b5c07ab0-b564-4537-9d0f-328d44a8d49b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_N5Xa0mx42",
    "aws_user_pools_web_client_id": "4aprvidqns0upnmdp28s33j2hj",
    "oauth": {}
};


export default awsmobile;
